kubelet-config custom parameters are missing after k8s upgrade
The kubernetes.pp class platform::kubernetes::upgrade_first_control_plane
which does 'kubeadm upgrade apply' resulted in versioned kubelet-config
ConfigMap. The pre-upgrade ConfigMap was left behind.

Having multiple ConfigMap causes 'system kube-config-kubelet' to fail,
so reconfiguration was broken.

In historical releases, we had specified '--config
/etc/kubernetes/kubelet_override.yaml', so the the kubelet garbage
collection eviction parameters became incorrect post k8s upgrade,
without a way to reconfigure.

This update will purge all kubelet-config ConfigMap except the most
recent. This occurs immediately following 'kubeadm upgrade apply' step.

Testplan:
PASS: AIO-SX perform k8s upgrade, run 'system kube-config-kubelet'.
      Verify only current version kubelet-config ConfigMap exists.

Closes-Bug: 2012975
Change-Id: I5e34299616690628267c07a744dc9923144e606d
Signed-off-by: Jim Gauld <James.Gauld@windriver.com>

diff --git a/puppet-manifests/src/modules/platform/templates/kube-config-kubelet.erb b/puppet-manifests/src/modules/platform/templates/kube-config-kubelet.erb
--- a/puppet-manifests/src/modules/platform/templates/kube-config-kubelet.erb
+++ b/puppet-manifests/src/modules/platform/templates/kube-config-kubelet.erb
@@ -15,11 +15,21 @@ s_exit() {
 cm_kubelet_tempfile=$(mktemp)
 
 <% if @is_controller_active.to_s == 'true' or @system_mode == 'simplex' -%>
-# Get current kubelet-config versioned configmap name
-cm_name=$(kubectl -n kube-system get configmaps -oname 2>/dev/null | \
-          awk '/kubelet-config/ {print $1}')
+# Get the most current kubelet-config versioned configmap name
+cm_name=$(kubectl -n kube-system get configmaps -oname \
+          --sort-by=.metadata.creationTimestamp 2>/dev/null)
 if [ $? -ne 0 ]; then
     echo "Get configmaps failed."
+    s_exit 1
+fi
+cm_name=$(grep -e kubelet-config <<< "${cm_name}" 2>/dev/null)
+if [ $? -ne 0 ]; then
+    echo "Could not find kubelet-config configmap."
+    s_exit 1
+fi
+cm_name=$(tail -n 1 <<< "${cm_name}" 2>/dev/null)
+if [ $? -ne 0 ]; then
+    echo "Could not get last kubelet-config configmap."
     s_exit 1
 fi
 echo "Got configmap: ${cm_name}"
